In [ ]:
import pandas as pd

DATA FRAMES CONCATINATION

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Claire"],
    "Age": [25, 30, 27],
    "Gender": ["Female", "Male", "Female"]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

     Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   27  Female

ADDING NEW ROW

In [ ]:
new_row = pd.DataFrame({"Name": "Harry","Age" : 40,"Gender": "Male"}, index=[3])

In [ ]:
df = pd.concat([df, new_row])

ADDING NEW COLUMN

In [ ]:
df["Job"] = ["Engg." , "Doctor", "Doctor", "Hacker"]

In [ ]:
df

     Name  Age  Gender     Job
0   Alice   25  Female   Engg.
1     Bob   30    Male  Doctor
2  Claire   27  Female  Doctor
3   Harry   40    Male  Hacker

MULTIPLE ROWS ADDITION

In [ ]:
new_rows = pd.DataFrame([{"Name": "Diljot","Age" : 40,"Gender": "Male", "Job": "Coder"},
                         {"Name": "Gaurav","Age" : 18,"Gender": "Male", "Job": "AIML Engineer"},
                         {"Name": "Harsh","Age" : 18,"Gender": "Male", "Job": "Coder"}], index=[4,5,6])

In [ ]:
df = pd.concat([df, new_rows])

In [ ]:
df

     Name  Age  Gender            Job
0   Alice   25  Female          Engg.
1     Bob   30    Male         Doctor
2  Claire   27  Female         Doctor
3   Harry   40    Male         Hacker
4  Diljot   40    Male          Coder
5  Gaurav   18    Male  AIML Engineer
6   Harsh   18    Male          Coder

CSV FILE

In [127]:
pokemon = pd.read_csv("pokemon.csv")

In [128]:
pokemon

          Name    Type 1  Type 2   HP  Attack  Defense  Speed
0    Bulbasaur     Grass  Poison   45      49       49     45
1      Ivysaur     Grass  Poison   60      62       63     60
2     Venusaur     Grass  Poison   80      82       83     80
3   Charmander      Fire     NaN   39      52       43     65
4   Charmeleon      Fire     NaN   58      64       58     80
5    Charizard      Fire  Flying   78      84       78    100
6     Squirtle     Water     NaN   44      48       65     43
7    Wartortle     Water     NaN   59      63       80     58
8    Blastoise     Water     NaN   79      83      100     78
9     Caterpie       Bug     NaN   45      30       35     45
10     Metapod       Bug     NaN   50      20       55     30
11  Butterfree       Bug  Flying   60      45       50     70
12     Pikachu  Electric     NaN   35      55       40     90
13      Raichu  Electric     NaN   60      90       55    110
14  Jigglypuff    Normal   Fairy  115      45       20     20
15      Gengar     Ghost  Poison   60      65       60    110
16        Onix      Rock  Ground   35      45      160     70
17       Eevee    Normal     NaN   55      55       50     55
18     Snorlax    Normal     NaN  160     110       65     30
19   Dragonite    Dragon  Flying   91     134       95     80

In [130]:
pokemon.isna()

     Name  Type 1  Type 2     HP  Attack  Defense  Speed
0   False   False   False  False   False    False  False
1   False   False   False  False   False    False  False
2   False   False   False  False   False    False  False
3   False   False    True  False   False    False  False
4   False   False    True  False   False    False  False
5   False   False   False  False   False    False  False
6   False   False    True  False   False    False  False
7   False   False    True  False   False    False  False
8   False   False    True  False   False    False  False
9   False   False    True  False   False    False  False
10  False   False    True  False   False    False  False
11  False   False   False  False   False    False  False
12  False   False    True  False   False    False  False
13  False   False    True  False   False    False  False
14  False   False   False  False   False    False  False
15  False   False   False  False   False    False  False
16  False   False   False  False   False    False  False
17  False   False    True  False   False    False  False
18  False   False    True  False   False    False  False
19  False   False   False  False   False    False  False

In [134]:
pokemon[["Name", "Type 1", "Type 2"]]

          Name    Type 1  Type 2
0    Bulbasaur     Grass  Poison
1      Ivysaur     Grass  Poison
2     Venusaur     Grass  Poison
3   Charmander      Fire     NaN
4   Charmeleon      Fire     NaN
5    Charizard      Fire  Flying
6     Squirtle     Water     NaN
7    Wartortle     Water     NaN
8    Blastoise     Water     NaN
9     Caterpie       Bug     NaN
10     Metapod       Bug     NaN
11  Butterfree       Bug  Flying
12     Pikachu  Electric     NaN
13      Raichu  Electric     NaN
14  Jigglypuff    Normal   Fairy
15      Gengar     Ghost  Poison
16        Onix      Rock  Ground
17       Eevee    Normal     NaN
18     Snorlax    Normal     NaN
19   Dragonite    Dragon  Flying

SUBSET SELECTION

In [142]:
pokemon.loc[[0,1,2]][["Name", "Type 1", "Type 2"]]

        Name Type 1  Type 2
0  Bulbasaur  Grass  Poison
1    Ivysaur  Grass  Poison
2   Venusaur  Grass  Poison

In [144]:
pokemon.loc[[19, 18 ,17]][["Name", "Type 1", "Type 2"]]

         Name  Type 1  Type 2
19  Dragonite  Dragon  Flying
18    Snorlax  Normal     NaN
17      Eevee  Normal     NaN

CONDITIONAL RENDERING

In [150]:
pokemon[pokemon["Type 1"] == "Fire"]

         Name Type 1  Type 2  HP  Attack  Defense  Speed
3  Charmander   Fire     NaN  39      52       43     65
4  Charmeleon   Fire     NaN  58      64       58     80
5   Charizard   Fire  Flying  78      84       78    100

In [152]:
pokemon[pokemon["Attack"] > 80]

         Name    Type 1  Type 2   HP  Attack  Defense  Speed
2    Venusaur     Grass  Poison   80      82       83     80
5   Charizard      Fire  Flying   78      84       78    100
8   Blastoise     Water     NaN   79      83      100     78
13     Raichu  Electric     NaN   60      90       55    110
18    Snorlax    Normal     NaN  160     110       65     30
19  Dragonite    Dragon  Flying   91     134       95     80