In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("pokemon.csv")

In [3]:
df

          Name    Type 1  Type 2   HP  Attack  Defense  Speed
0    Bulbasaur     Grass  Poison   45      49       49     45
1      Ivysaur     Grass  Poison   60      62       63     60
2     Venusaur     Grass  Poison   80      82       83     80
3   Charmander      Fire     NaN   39      52       43     65
4   Charmeleon      Fire     NaN   58      64       58     80
5    Charizard      Fire  Flying   78      84       78    100
6     Squirtle     Water     NaN   44      48       65     43
7    Wartortle     Water     NaN   59      63       80     58
8    Blastoise     Water     NaN   79      83      100     78
9     Caterpie       Bug     NaN   45      30       35     45
10     Metapod       Bug     NaN   50      20       55     30
11  Butterfree       Bug  Flying   60      45       50     70
12     Pikachu  Electric     NaN   35      55       40     90
13      Raichu  Electric     NaN   60      90       55    110
14  Jigglypuff    Normal   Fairy  115      45       20     20
15      Gengar     Ghost  Poison   60      65       60    110
16        Onix      Rock  Ground   35      45      160     70
17       Eevee    Normal     NaN   55      55       50     55
18     Snorlax    Normal     NaN  160     110       65     30
19   Dragonite    Dragon  Flying   91     134       95     80

In [4]:
df.isna()

     Name  Type 1  Type 2     HP  Attack  Defense  Speed
0   False   False   False  False   False    False  False
1   False   False   False  False   False    False  False
2   False   False   False  False   False    False  False
3   False   False    True  False   False    False  False
4   False   False    True  False   False    False  False
5   False   False   False  False   False    False  False
6   False   False    True  False   False    False  False
7   False   False    True  False   False    False  False
8   False   False    True  False   False    False  False
9   False   False    True  False   False    False  False
10  False   False    True  False   False    False  False
11  False   False   False  False   False    False  False
12  False   False    True  False   False    False  False
13  False   False    True  False   False    False  False
14  False   False   False  False   False    False  False
15  False   False   False  False   False    False  False
16  False   False   False  False   False    False  False
17  False   False    True  False   False    False  False
18  False   False    True  False   False    False  False
19  False   False   False  False   False    False  False

In [5]:
df.isna().sum()

Name        0
Type 1      0
Type 2     11
HP          0
Attack      0
Defense     0
Speed       0
dtype: int64

In [9]:
df.fillna(value={"Type 2":"None"})

          Name    Type 1  Type 2   HP  Attack  Defense  Speed
0    Bulbasaur     Grass  Poison   45      49       49     45
1      Ivysaur     Grass  Poison   60      62       63     60
2     Venusaur     Grass  Poison   80      82       83     80
3   Charmander      Fire    None   39      52       43     65
4   Charmeleon      Fire    None   58      64       58     80
5    Charizard      Fire  Flying   78      84       78    100
6     Squirtle     Water    None   44      48       65     43
7    Wartortle     Water    None   59      63       80     58
8    Blastoise     Water    None   79      83      100     78
9     Caterpie       Bug    None   45      30       35     45
10     Metapod       Bug    None   50      20       55     30
11  Butterfree       Bug  Flying   60      45       50     70
12     Pikachu  Electric    None   35      55       40     90
13      Raichu  Electric    None   60      90       55    110
14  Jigglypuff    Normal   Fairy  115      45       20     20
15      Gengar     Ghost  Poison   60      65       60    110
16        Onix      Rock  Ground   35      45      160     70
17       Eevee    Normal    None   55      55       50     55
18     Snorlax    Normal    None  160     110       65     30
19   Dragonite    Dragon  Flying   91     134       95     80