In [1]:
import numpy as np
import pandas as pd

**DataFrame**

In [2]:
students = {
    "roll_no": [101, 102, 103, 104],
    "name": ["Amit", "Neha", "Rohit", "Simran"],
    "course": ["BCA", "BTech", "BSc", "MCA"],
    "marks": [85, 92, 78, 88]
}

df = pd.DataFrame(students)    # With Dictionary

In [3]:
df

   roll_no    name course  marks
0      101    Amit    BCA     85
1      102    Neha  BTech     92
2      103   Rohit    BSc     78
3      104  Simran    MCA     88

**DataFrame2**

In [4]:
data = {
    "id": [1, 2, 3, 4],
    "name": ["Gaurav", "Rahul", "Aman", "Priya"],
    "age": [21, 22, 20, 23],
    "city": ["Delhi", "Mumbai", "Chandigarh", "Pune"]
}

df2 = pd.DataFrame(data)       # With Dictionary
df2

   id    name  age        city
0   1  Gaurav   21       Delhi
1   2   Rahul   22      Mumbai
2   3    Aman   20  Chandigarh
3   4   Priya   23        Pune

In [5]:
employees = [
    [1, "John", "IT", 60000],
    [2, "Sarah", "HR", 50000],
    [3, "Mike", "Finance", 70000],
    [4, "Emma", "IT", 65000]
]

**DataFrame3**

In [6]:
df3 = pd.DataFrame(employees)   # With list

In [7]:
df3

   0      1        2      3
0  1   John       IT  60000
1  2  Sarah       HR  50000
2  3   Mike  Finance  70000
3  4   Emma       IT  65000

**DataFrame4**

In [10]:
column = ["Id", "Name", "Branch" , "Salary"]
df4 = pd.DataFrame(employees, columns=column)

In [11]:
df4

   Id   Name   Branch  Salary
0   1   John       IT   60000
1   2  Sarah       HR   50000
2   3   Mike  Finance   70000
3   4   Emma       IT   65000

**Selection And Indexing**

In [12]:
df2

   id    name  age        city
0   1  Gaurav   21       Delhi
1   2   Rahul   22      Mumbai
2   3    Aman   20  Chandigarh
3   4   Priya   23        Pune

In [14]:
df2["name"]

0    Gaurav
1     Rahul
2      Aman
3     Priya
Name: name, dtype: str

In [15]:
df2[["name", "city"]]

     name        city
0  Gaurav       Delhi
1   Rahul      Mumbai
2    Aman  Chandigarh
3   Priya        Pune

In [16]:
df2["Designation"] = ["AIML Engineer", "Engineer" , "Doctor", "Doctor"]

In [17]:
df2

   id    name  age        city    Designation
0   1  Gaurav   21       Delhi  AIML Engineer
1   2   Rahul   22      Mumbai       Engineer
2   3    Aman   20  Chandigarh         Doctor
3   4   Priya   23        Pune         Doctor

In [18]:
df2.drop("age", axis=1)

   id    name        city    Designation
0   1  Gaurav       Delhi  AIML Engineer
1   2   Rahul      Mumbai       Engineer
2   3    Aman  Chandigarh         Doctor
3   4   Priya        Pune         Doctor

In [23]:
df2.drop(["city", "id"], axis=1)

     name    Designation
0  Gaurav  AIML Engineer
1   Rahul       Engineer
2    Aman         Doctor
3   Priya         Doctor

In [19]:
df2

   id    name  age        city    Designation
0   1  Gaurav   21       Delhi  AIML Engineer
1   2   Rahul   22      Mumbai       Engineer
2   3    Aman   20  Chandigarh         Doctor
3   4   Priya   23        Pune         Doctor

In [20]:
df2.drop("age", axis=1, inplace= True)

In [21]:
df2

   id    name        city    Designation
0   1  Gaurav       Delhi  AIML Engineer
1   2   Rahul      Mumbai       Engineer
2   3    Aman  Chandigarh         Doctor
3   4   Priya        Pune         Doctor

In [24]:
df2.drop(0, axis=0)

   id   name        city Designation
1   2  Rahul      Mumbai    Engineer
2   3   Aman  Chandigarh      Doctor
3   4  Priya        Pune      Doctor

**Selecting Rows**

In [25]:
df2

   id    name        city    Designation
0   1  Gaurav       Delhi  AIML Engineer
1   2   Rahul      Mumbai       Engineer
2   3    Aman  Chandigarh         Doctor
3   4   Priya        Pune         Doctor

In [26]:
df2.loc[0]

id                         1
name                  Gaurav
city                   Delhi
Designation    AIML Engineer
Name: 0, dtype: object

In [27]:
df2.loc[[2,1]]

   id   name        city Designation
2   3   Aman  Chandigarh      Doctor
1   2  Rahul      Mumbai    Engineer

In [31]:
df2.iloc[[3,1]]

   id   name    city Designation
3   4  Priya    Pune      Doctor
1   2  Rahul  Mumbai    Engineer

**Selecting Subset of Rows and Columns**