In [2]:
import numpy as np
import pandas as pd

In [32]:
data = [
    [1,2,3,4,5],
    [np.nan, 2,3,np.nan,5],
    [np.nan, 2 ,np.nan, 4, 5],
    [1, 2, 3, 4, np.nan],
]

In [33]:
col = ["A", "B", "C", "D", "E"]
df = pd.DataFrame(data, columns=col)

In [34]:
df

     A  B    C    D    E
0  1.0  2  3.0  4.0  5.0
1  NaN  2  3.0  NaN  5.0
2  NaN  2  NaN  4.0  5.0
3  1.0  2  3.0  4.0  NaN

**Missing Values**

In [49]:
df.isna()  #Check null values exist or not

       A      B      C      D      E
0  False  False  False  False  False
1   True  False  False   True  False
2   True  False   True  False  False
3  False  False  False  False   True

In [36]:
df.isna().sum()

A    2
B    0
C    1
D    1
E    1
dtype: int64

**Deleting Missing Values + Threshold**

In [41]:
df.dropna(thresh=4)    # The rows which have atleast 4 non null values

     A  B    C    D    E
0  1.0  2  3.0  4.0  5.0
3  1.0  2  3.0  4.0  NaN

In [43]:
df.dropna()   # Delete the rows which have null values

     A  B    C    D    E
0  1.0  2  3.0  4.0  5.0

**Fill Missing Values**

In [48]:
df.fillna(0)  # Fill the null values

     A  B    C    D    E
0  1.0  2  3.0  4.0  5.0
1  0.0  2  3.0  0.0  5.0
2  0.0  2  0.0  4.0  5.0
3  1.0  2  3.0  4.0  0.0